#!/usr/bin/env python3
"""Generate build artifacts from compute_version (C header, Vite env file)."""

from __future__ import annotations

import argparse
import sys
from datetime import UTC, datetime
from pathlib import Path

_SCRIPTS_DIR = Path(__file__).resolve().parent
if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))

from compute_version import VersionInfo, compute_version


def _render_c_header(info: VersionInfo) -> str:
    return f"""\
/* Generated by scripts/generate_version.py — do not edit. */
#ifndef AVAR_VERSION_H
#define AVAR_VERSION_H

#define AVAR_VERSION_MAJOR {info.major}
#define AVAR_VERSION_MINOR {info.minor}
#define AVAR_VERSION_REVISION {info.revision}
#define VERSION_STR "{info.version}"
#define AVAR_VERSION_COMMIT "{info.commit}"

#endif /* AVAR_VERSION_H */
"""


def _render_env(info: VersionInfo, *, build_date: str) -> str:
    lines = [
        f"VITE_BUILD_VERSION={info.version}",
        f"VITE_BUILD_DATE={build_date}",
    ]
    if info.commit:
        lines.append(f"VITE_BUILD_COMMIT={info.commit}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
        help="Repository root",
    )
    parser.add_argument("--out-c-header", type=Path, help="Write C version header")
    parser.add_argument("--out-env", type=Path, help="Write Vite .env variables")
    args = parser.parse_args()

    root = args.root.resolve()
    if not args.out_c_header and not args.out_env:
        parser.error("At least one of --out-c-header or --out-env is required")

    try:
        info = compute_version(root)
    except (ValueError, OSError) as exc:
        print(exc, file=sys.stderr)
        return 1

    build_date = datetime.now(UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")

    if args.out_c_header:
        out = args.out_c_header.resolve()
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(_render_c_header(info), encoding="utf-8", newline="\n")
        print(f"Wrote {out}", flush=True)

    if args.out_env:
        out = args.out_env.resolve()
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(_render_env(info, build_date=build_date), encoding="utf-8", newline="\n")
        print(f"Wrote {out}", flush=True)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
